### PR TITLE
Tx parser update

### PR DESCRIPTION
**Pull request by Sajjon**
This contains breaking changes to the TX structure/model.

Must coordinate and merge [corresponding PR of  C code in Ledger app repo](https://github.com/radixdlt/app-radix/pull/11)

You must know which Network is compatible with these updates.

These updates should be on-par [with @iamyulong s update of Core (see PR)](https://github.com/radixdlt/radixdlt/pull/361).

All these changes must be ported to Leger app.

@siy The file `txParser.test.ts` contains an outcommented line:
```js
describe('txParser', () => {
	afterAll(() => {
		// Use log below to output C unit tests string.
		// 	console.log(c_unit_tests_string)
	})
....
}
```

So comment in that line, and run that test file, you can do that with:
```sh
yarn build && yarn test -t 'txParser'
```

This is the fastest way to generate unit tests in C for transactions we expect to be able to parse.

### CODE REVIEW

**Comment by Sajjon** [comment]
@AbstractFruitFactory  Alex can you help @siy to get integration test running, especially the command:

```sh
yarn test:ledger:hw
```

Sergiy you will need to call:
```sh
yarn workspace @radixdlt/hardware-ledger add @aleworm/hw-transport-node-hid
```

Because we have not included this dependency as part of version control, because of earlier issues with CI.

Maybe this is not an issue anymore @AbstractFruitFactory ? :)

**Comment by Sajjon** [comment]
Status: I think it is ready to be merged... when deemed suitable.

**Comment by iamyulong** [comment]
Hey @sajjon, Josh introduced some slight changes just minutes ago. Do you think it's worth to include that as well? It's believed to be the very last change.

It's about the code of instructions.

**Comment by Sajjon** [comment]
@iamyulong (for sake of public ref) these PR is now in the safe hands of @AbstractFruitFactory 

@AbstractFruitFactory let @iamyulong help you getting Rust up on your machine, so that you can run the tests in the [Rust Docs folder here](https://github.com/radixdlt/radixdlt/tree/rc/1.0-beta.37/docs/transaction-specs)

The repo contains `.txt` files containing the TX BLOB. But you need to run the test to get the output.  E.g running test  which test blob found in`xrd_transfer_with_msg.txt` (you run single test by matching name, using command `cargo test xrd_transfer_with_msg -- --nocapture`)

which contains tx blob:
`0a000104973b739777f86d706b1ff85aaab35065e8de03da0fe83bbedf30a0acc0ec4ea5000000010921000000000000000000000000000000000000000000000000000de0b6b3a76400000105000402935deebcad35bcf27d05b431276be8fcba26312cd1d54c33ac6748a72fe427ca0100000000000000000000000000000000000000000000d38ba0a18da57d6c00000005000000000105000402935deebcad35bcf27d05b431276be8fcba26312cd1d54c33ac6748a72fe427ca0100000000000000000000000000000000000000000000d38b5b3dfc2338780000010500040356959464545aa2787984fe4ac76496721a22f150c0076724ad7190fe3a597bb7010000000000000000000000000000000000000000000000004563918244f40000000921010000000000000000000000000000000000000000000000000de0b6b3a76400000105000402935deebcad35bcf27d05b431276be8fcba26312cd1d54c33ac6748a72fe427ca010000000000000000000000000000000000000000000000000de0b6b3a764000000060548656c6c6f07011fb6a9ee8ff5a1268c714bc2ac8b6df40479b413b2d294721dbad90b188f74cc61fafc48ba910b47ad38de381188bb271903045f037e332010b6bb54cc289702`

```sh
$ pwd
/Users/sajjon/Developer/Java/radixdlt/docs/transaction-specs/test/parser

~/Developer/Java/radixdlt/docs/transaction-specs/test/parser on  feature/update-specs-2021-06-28 ⌚ 18:03:57
$ cargo test xrd_transfer_with_msg -- --nocapture
    Finished test [unoptimized + debuginfo] target(s) in 0.01s
     Running unittests (target/debug/deps/parser-d190bc4351647084)

running 1 test
Instructions:
|- HEADER(0, 1)
|- DOWN(SubstateId { hash: 0x973b739777f86d706b1ff85aaab35065e8de03da0fe83bbedf30a0acc0ec4ea5, index: 1 })
|- SYSCALL(0x000000000000000000000000000000000000000000000000000de0b6b3a7640000)
|- UP(Tokens { reserved: 0, owner: 0x0402935deebcad35bcf27d05b431276be8fcba26312cd1d54c33ac6748a72fe427ca, resource: 0x01, amount: U256 { raw: 998995000000000000000000 } })
|- END
|- LDOWN(0)
|- UP(Tokens { reserved: 0, owner: 0x0402935deebcad35bcf27d05b431276be8fcba26312cd1d54c33ac6748a72fe427ca, resource: 0x01, amount: U256 { raw: 998990000000000000000000 } })
|- UP(Tokens { reserved: 0, owner: 0x040356959464545aa2787984fe4ac76496721a22f150c0076724ad7190fe3a597bb7, resource: 0x01, amount: U256 { raw: 5000000000000000000 } })
|- END
|- SYSCALL(0x010000000000000000000000000000000000000000000000000de0b6b3a7640000)
|- UP(Tokens { reserved: 0, owner: 0x0402935deebcad35bcf27d05b431276be8fcba26312cd1d54c33ac6748a72fe427ca, resource: 0x01, amount: U256 { raw: 1000000000000000000 } })
|- END
|- MSG(0x48656c6c6f)
|- SIG(0x011fb6a9ee8ff5a1268c714bc2ac8b6df40479b413b2d294721dbad90b188f74cc61fafc48ba910b47ad38de381188bb271903045f037e332010b6bb54cc289702)

test transaction::tests::xrd_transfer_with_msg ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 13 filtered out; finished in 0.00s


~/Developer/Java/radixdlt/docs/transaction-specs/test/parser on  feature/update-specs-2021-06-28 ⌚ 18:03:59
```

I than take the outputted instruction, as a whole:

```
Instructions:
|- HEADER(0, 1)
|- DOWN(SubstateId { hash: 0x973b739777f86d706b1ff85aaab35065e8de03da0fe83bbedf30a0acc0ec4ea5, index: 1 })
|- SYSCALL(0x000000000000000000000000000000000000000000000000000de0b6b3a7640000)
|- UP(Tokens { reserved: 0, owner: 0x0402935deebcad35bcf27d05b431276be8fcba26312cd1d54c33ac6748a72fe427ca, resource: 0x01, amount: U256 { raw: 998995000000000000000000 } })
|- END
|- LDOWN(0)
|- UP(Tokens { reserved: 0, owner: 0x0402935deebcad35bcf27d05b431276be8fcba26312cd1d54c33ac6748a72fe427ca, resource: 0x01, amount: U256 { raw: 998990000000000000000000 } })
|- UP(Tokens { reserved: 0, owner: 0x040356959464545aa2787984fe4ac76496721a22f150c0076724ad7190fe3a597bb7, resource: 0x01, amount: U256 { raw: 5000000000000000000 } })
|- END
|- SYSCALL(0x010000000000000000000000000000000000000000000000000de0b6b3a7640000)
|- UP(Tokens { reserved: 0, owner: 0x0402935deebcad35bcf27d05b431276be8fcba26312cd1d54c33ac6748a72fe427ca, resource: 0x01, amount: U256 { raw: 1000000000000000000 } })
|- END
|- MSG(0x48656c6c6f)
|- SIG(0x011fb6a9ee8ff5a1268c714bc2ac8b6df40479b413b2d294721dbad90b188f74cc61fafc48ba910b47ad38de381188bb271903045f037e332010b6bb54cc289702)
```

And let it be the value of `parsedTX` as input in `TestVector` object passed to `doTestParseTX` in `txParser.test.ts`
_**You need to delete the last instruction, `SIG`**_ however. And that SIG bytes from the blob. Lookup the INSTRUCTION CODE for SIG, right now it is `07`, and from out put above you see `SIG(0x011fb6a....702)` meaning that you should remove the hex:
`07011fb6a9ee8ff5a1268c714bc2ac8b6df40479b413b2d294721dbad90b188f74cc61fafc48ba910b47ad38de381188bb271903045f037e332010b6bb54cc289702` from the blob.

The HASHes I put there is computed by the JS test itself... it is just the SHA256 twice of the blob...

The `owner` of tokens starts with `0x04` and then a 33 bytes public key hex. If that matches the value of prop `myPublicKeyHex` in TestVector, it means that the `amount` of those tokens will NOT count towards TOTAL XRD SPENT, because those tokens are "change back to user". So I just use that property `myPublicKeyHex` as a flag to try logic for including or excluding amounts.

@iamyulong and @talekhinezh will help you explaining TX FEE. It involves the SYSCALL(s). but in short: `SYSCALL(00 + amountPUT) - sumOf([ SYSCALL(01+ amountTake0), SYSCALL(01+ amountTake1), SYSCALL(01+ amountTake2), ...SYSCALL(01+ amountTakeN-1) ]` 

N.B. that many of @iamyulong s test vectors contained TX which are structurally valid, but semanitcally invalid, because they contained same amount of `SYSCALL(01+ amountPUT)` and `SYSCALL(01+ amountTake)`, resulting in a tx fee of 0. Which is invalid.

So I have MANUALLY increased side of ``SYSCALL(00 + amountPUT)` by adding `abba` before `de0b6b3a7640000` (1000000000000000000 dec). i.e. changing BOTH in text (prop `parsedTX`)
`SYSCALL(0x000000000000000000000000000000000000000000000000000de0b6b3a7640000)` into SYSCALL(0x00000000000000000000000000000000000000000000000abbade0b6b3a7640000)

and in BLOB HEX:
`0921000000000000000000000000000000000000000000000000000de0b6b3a7640000` into
`092100000000000000000000000000000000000000000000000abbade0b6b3a7640000`
.

Finally for `totalXRDAmount` I've manually looked at the amounts of all TOKENs up having `owner !== myPublicKeyHex` summed them up using WolframAlpha and added txFEE.

Once all valid, you can help @siy add the new unit test to C code. by use of function `generate_ledger_app_unit_test_c_code_from_test_vector`.

**Comment by iamyulong** [comment]
Following https://github.com/radixdlt/radixdlt/pull/361, we've made three additional changes:
- https://github.com/radixdlt/radixdlt/pull/373
- https://github.com/radixdlt/radixdlt/pull/384
- https://github.com/radixdlt/radixdlt/pull/397

**Pull request merged**
